### PR TITLE
Exception Handling / Some renaming

### PR DESCRIPTION
**Pull request by tringler**
Hello,

would be nice if we can bring that PR to the master / pyPi package.

Thanks, Tom

### CODE REVIEW

**Comment by ITTV-tools** [comment]
done 👍

**Comment by tringler** [comment]
Thanks for that fast merge!

**Comment by tringler** [comment]
But somehow the `README.md` seems not to be merged - Do you have an idea why?

**Comment by ITTV-tools** [comment]
I changed it by accident (fixed now)

**Pull request merged**
